repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: [css, markdown, text, svg]
      - id: trailing-whitespace
        exclude_types: [html, markdown, text]
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        language: python
        types: [python]
        args: ["--config=pyproject.toml"]
  - repo: local
    hooks:
      - id: codespell
        name: codespell
        entry: codespell
        language: python
        types: [text]