"""Helpers Module"""

__docformat__ = "google"

import re
from io import BytesIO
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import polars as pl
import requests

from financedatabase import logger_model
from financedatabase.data_loader import (
    HEADERS,
    from_pandas,
    load_lazy,
    string_dtype,
    to_pandas,
)

# pylint: disable=isinstance-second-argument-not-valid-type

# Displays notices, such as a filter that found no primary listings.
logger_model.setup_logger()
logger = logger_model.get_logger()

# Location of the compressed database files when use_local_location=True.
COMPRESSION_PATH = Path(__file__).parent.parent / "compression"

# The compressed files are regenerated by GitHub Actions on every update of main.
DATA_REPO = (
    "https://raw.githubusercontent.com/JerBouma/FinanceDatabase/main/compression/"
)

# Added to a frame assigned to .data so results can be taken from it by row position.
ROW_POSITION = "__financedatabase_row__"

# Shown when a database file can't be downloaded.
LOAD_ERROR_HINT = (
    "Ensure you are able to access the file. "
    "It is possible it fails due to a firewall or other security settings. "
    "Sometimes Google Colab is also the culprit."
)


class FinanceFrame(pd.DataFrame):
    """
    Enhanced DataFrame with financial data integration capabilities.

    Extends the pandas DataFrame with additional functionality for
    financial analysis, particularly for connecting with the Finance
    Toolkit using tickers obtained from the Finance Database.
    """

    def to_toolkit(
        self,
        api_key: str | None = None,
        start_date: str | None = None,
        end_date: str | None = None,
        quarterly: bool = False,
        use_cached_data: bool | str = False,
        risk_free_rate: str = "10y",
        benchmark_ticker: str | None = "SPY",
        enforce_source: str | None = None,
        convert_currency: bool | None = None,
        intraday_period: str | None = None,
        rounding: int | None = 4,
        remove_invalid_tickers: bool = False,
        sleep_timer: bool | None = None,
        progress_bar: bool = True,
    ) -> Any:
        """
        Convert the FinanceFrame to a Finance Toolkit object.

        Creates a Finance Toolkit object using the tickers in this DataFrame,
        providing access to fundamental and historical data, ratios, metrics,
        models, and technical indicators.

        Args:
            api_key (str | None, optional): API key from FinancialModelingPrep.
                Obtain one at: https://www.jeroenbouma.com/fmp. Defaults to None.
            start_date (str | None, optional): Start date for data collection (YYYY-MM-DD).
                Defaults to 10 years before the current date.
            end_date (str | None, optional): End date for data collection (YYYY-MM-DD).
                Defaults to the current date.
            quarterly (bool, optional): Whether to collect quarterly financial statements.
                Defaults to False (yearly statements).
            use_cached_data (bool | str, optional): Whether to use previously cached data.
                Can be a boolean or a string path. Defaults to False.
            risk_free_rate (str, optional): Risk-free rate to use (13w, 5y, 10y, 30y).
                Based on US Treasury Yields. Defaults to "10y".
            benchmark_ticker (str | None, optional): Ticker for benchmark comparisons.
                Defaults to "SPY" (S&P 500).
            enforce_source (str | None, optional): Source for the data ("FinancialModelingPrep"
                or "YahooFinance"). Defaults to None (both are used).
            convert_currency (bool | None, optional): Whether to convert financial statement
                currencies to match historical data. Defaults to None (auto-determined).
            intraday_period (str | None, optional): Time period for intraday data (1min, 5min,
                15min, 30min, 1hour). Defaults to None.
            rounding (int | None, optional): Number of decimal places for results. Defaults to 4.
            remove_invalid_tickers (bool, optional): Whether to remove invalid tickers.
                Defaults to False.
            sleep_timer (bool | None, optional): Whether to use a sleep timer when the rate
                limit is reached. Defaults to None (auto-determined).
            progress_bar (bool, optional): Whether to show a progress bar for 10+ tickers.
                Defaults to True.

        Returns:
            Toolkit: Finance Toolkit object with data for the tickers in this DataFrame.

        Raises:
            ImportError: If the Finance Toolkit is not installed.

        As an example:

        ```python
        import financedatabase as fd

        equities = fd.Equities()

        toolkit = equities.select(country="Netherlands", sector="Financials").to_toolkit(
            api_key="FINANCIAL_MODELING_PREP_KEY"
        )

        toolkit.ratios.get_profitability_ratios()
        ```
        """
        try:
            # Lazy import: financetoolkit is an optional dependency.
            from financetoolkit import (  # noqa: PLC0415 # pylint: disable=import-outside-toplevel
                Toolkit,
            )
        except ImportError as exc:
            raise ImportError(
                "To use the 'to_toolkit' functionality, it requires installation of the FinanceToolkit "
                "Please use: \033[1m pip install financetoolkit -U \033[0m"
            ) from exc
        if api_key is None:
            logger.info(
                "The parameter api_key is not set. Therefore, using Yahoo Finance as the source which "
                "is limited to 5 years of fundamental data. Consider obtaining a key with the following "
                "link: https://www.jeroenbouma.com/fmp"
                "\nYou can get 15% off by using the above affiliate link to "
                "get access to 30+ years of (quarterly) data which also supports the project."
            )

        symbols = self[self.index.notna()].index.to_list()

        toolkit = Toolkit(
            tickers=symbols,
            api_key=api_key or "",
            start_date=start_date,
            end_date=end_date,
            quarterly=quarterly,
            use_cached_data=use_cached_data,
            risk_free_rate=risk_free_rate,
            benchmark_ticker=benchmark_ticker,
            enforce_source=enforce_source,
            convert_currency=convert_currency,
            intraday_period=intraday_period,
            rounding=rounding,
            remove_invalid_tickers=remove_invalid_tickers,
            sleep_timer=sleep_timer,
            progress_bar=progress_bar,
        )

        return toolkit


class FinanceDatabase:
    """
    The FinanceDatabase provides free categorization of all types of financial products.
    It features over 300,000 symbols containing Equities, ETFs, Funds, Indices,
    Currencies, Cryptocurrencies, and Money Markets, offering a comprehensive overview
    of sectors, industries, investment types, and more.

    This class serves as the base controller for all asset-class specific subclasses.
    Data is cached locally and queried lazily with Polars (see the Data Loader module);
    results are returned as pandas (as_pandas=True, the default) or Polars DataFrames.
    """

    FILE_NAME = ""
    # Selectable columns in select() parameter order: column -> (label, plural) for the
    # "The <label> '<value>' is not available ... the available <plural>" error message.
    FIELDS: dict[str, tuple[str, str]] = {}
    # Whether filter values are validated against listed entries only. None follows the
    # exclude_delisted argument; True always validates against listed entries.
    VALIDATION_EXCLUDES_DELISTED: bool | None = None
    # Name used in the notice shown when only_primary_listing finds no primary listings.
    PLURAL_NAME = ""

    def __init__(
        self,
        base_url: str = DATA_REPO,
        use_local_location: bool = False,
    ) -> None:
        """
        Initialize the FinanceDatabase object.

        Loads the database for the asset class from the local cache, downloading it first
        when it isn't cached yet (or when the published file changed; checked at most once
        a day). Queries only read what they need.

        Args:
            base_url (str, optional): The URL or local path to the compressed files.
                Defaults to the GitHub repository location.
            use_local_location (bool, optional): Whether to use the compressed files of a
                local copy of the repository instead of the URL. Defaults to False.

        Raises:
            ValueError: If the data can't be loaded from the specified location.

        As an example:

        ```python
        import financedatabase as fd

        equities = fd.Equities()
        ```
        """
        the_path = str(COMPRESSION_PATH) + "/" if use_local_location else base_url
        the_path += self.FILE_NAME
        try:
            self._lazy = load_lazy(
                self.FILE_NAME,
                base_url,
                COMPRESSION_PATH if use_local_location else None,
            )
        except requests.exceptions.RequestException as error:
            raise ValueError(
                f"Failed to load data from {the_path}: {str(error)}.\n{LOAD_ERROR_HINT}"
            ) from error
        self._data: pd.DataFrame | None = None
        self._options_cache: dict[tuple[str, bool], set[str]] = {}
        self._empty_columns: set[str] | None = None

    @property
    def data(self) -> pd.DataFrame:
        """
        Get the full dataset as a pandas DataFrame, built on first access and then kept.

        Returns:
            pd.DataFrame: Every row of the asset class, indexed by symbol.
        """
        if self._data is None:
            self._data = self._to_pandas(self._lazy.collect())
        return self._data

    @data.setter
    def data(self, frame: pd.DataFrame) -> None:
        """
        Replace the dataset, for example with a filtered or modified copy.

        Queries run on a text copy; results are taken from the given frame by row
        position, so they keep its exact index and dtypes.

        Args:
            frame (pd.DataFrame): The dataset to query from now on.
        """
        self._data = frame
        self._lazy = (
            from_pandas(frame)
            .with_columns(pl.int_range(pl.len(), dtype=pl.Int64).alias(ROW_POSITION))
            .lazy()
        )
        self._options_cache = {}
        self._empty_columns = None

    def _to_pandas(self, frame: pl.DataFrame) -> pd.DataFrame:
        """
        Convert a collected Polars frame to the pandas frame the package always returned.

        Args:
            frame (pl.DataFrame): The collected rows.

        Returns:
            pd.DataFrame: The rows with the dtypes pandas' CSV reader would give them.
        """
        result = to_pandas(frame)
        # pandas' CSV reader types a column that is empty in the whole file as float64.
        if self._empty_columns is None:
            counts = self._lazy.select(pl.all().is_not_null().sum()).collect().row(0)
            self._empty_columns = {
                name
                for name, count in zip(self._lazy.collect_schema(), counts)
                if not count
            }
        for name in self._empty_columns:
            if name in result.columns:
                result[name] = result[name].astype("float64")
        return result

    def _output(
        self, frame: pl.DataFrame, as_pandas: bool
    ) -> FinanceFrame | pl.DataFrame:
        """
        Return the collected rows in the format the user asked for.

        Args:
            frame (pl.DataFrame): The collected rows.
            as_pandas (bool): Whether to return a pandas (FinanceFrame) or Polars DataFrame.

        Returns:
            FinanceFrame | pl.DataFrame: The rows as a FinanceFrame or Polars DataFrame.
        """
        # The data was replaced with a pandas frame, so rows are taken from it by position.
        if ROW_POSITION in frame.columns:
            if as_pandas:
                positions = frame.get_column(ROW_POSITION).to_list()
                return FinanceFrame(self._data.iloc[positions])
            return frame.drop(ROW_POSITION)
        return FinanceFrame(self._to_pandas(frame)) if as_pandas else frame

    def _without_delisted(self, exclude_delisted: bool) -> pl.LazyFrame:
        """
        Get the lazy dataset, without delisted entries when requested.

        Args:
            exclude_delisted (bool): Whether to drop rows marked as delisted.

        Returns:
            pl.LazyFrame: The lazy dataset.
        """
        lazy = self._lazy
        if exclude_delisted and "delisted" in lazy.collect_schema():
            lazy = lazy.filter(pl.col("delisted") != "True")
        return lazy

    def _options_lower(self, field: str, exclude_delisted: bool) -> set[str]:
        """
        Get the lowercase values of a column, cached per instance.

        Args:
            field (str): The column name.
            exclude_delisted (bool): Whether to leave out values of delisted entries.

        Returns:
            set[str]: The unique lowercase values of the column.
        """
        key = (field, exclude_delisted)
        if key not in self._options_cache:
            values = (
                self._without_delisted(exclude_delisted)
                .select(pl.col(field).drop_nulls().str.to_lowercase().unique())
                .collect()
                .get_column(field)
            )
            self._options_cache[key] = set(values.to_list())
        return self._options_cache[key]

    def _filtered(
        self,
        filters: dict[str, Any],
        only_primary_listing: bool = False,
        exclude_delisted: bool = False,
    ) -> pl.LazyFrame:
        """
        Validate the filters and apply them lazily.

        Args:
            filters (dict[str, Any]): Column name to a value or list of values.
            only_primary_listing (bool, optional): Whether to only keep symbols without an
                exchange suffix. Defaults to False.
            exclude_delisted (bool, optional): Whether to drop delisted entries.
                Defaults to False.

        Returns:
            pl.LazyFrame: The lazy dataset with the filters applied.

        Raises:
            ValueError: If a filter value is not available in the database.
        """
        lazy = self._without_delisted(exclude_delisted)
        for field, (label, plural) in self.FIELDS.items():
            value = filters.get(field)
            if not value:
                continue
            values = [value] if isinstance(value, str) else value
            values_lower = [item.lower() for item in values]
            validate_listed = self.VALIDATION_EXCLUDES_DELISTED
            options = self._options_lower(
                field, exclude_delisted if validate_listed is None else validate_listed
            )
            for item_lower, item in zip(values_lower, values):
                if item_lower not in options:
                    raise ValueError(
                        f"The {label} '{item}' is not available in the database. "
                        f"Please check the available {plural} using the 'show_options' method."
                    )
            lazy = lazy.filter(pl.col(field).str.to_lowercase().is_in(values_lower))
        if only_primary_listing:
            symbol = self._lazy.collect_schema().names()[0]
            primary = lazy.filter(~pl.col(symbol).str.contains(".", literal=True))
            # If there are no primary listings, all listings are returned instead.
            if primary.select(pl.len()).collect().item():
                lazy = primary
            else:
                logger.info(
                    "No primary listings found. Returning all %s matching your criteria.",
                    self.PLURAL_NAME,
                )
        return lazy

    def _select(
        self,
        filters: dict[str, Any],
        only_primary_listing: bool = False,
        exclude_delisted: bool = False,
        as_pandas: bool = True,
    ) -> FinanceFrame | pl.DataFrame:
        """
        Collect the rows matching the filters, the shared body of every select().

        Args:
            filters (dict[str, Any]): Column name to a value or list of values.
            only_primary_listing (bool, optional): Whether to only keep primary listings.
                Defaults to False.
            exclude_delisted (bool, optional): Whether to drop delisted entries.
                Defaults to False.
            as_pandas (bool, optional): Whether to return a pandas DataFrame.
                Defaults to True.

        Returns:
            FinanceFrame | pl.DataFrame: The matching rows.
        """
        lazy = self._filtered(filters, only_primary_listing, exclude_delisted)
        return self._output(lazy.collect(), as_pandas)

    def _show_options(
        self,
        selection: str | None,
        selection_values: list[str],
        invalid_selection_message: str,
        filters: dict[str, Any],
        exclude_delisted: bool = False,
        as_pandas: bool = True,
    ) -> dict | np.ndarray | pl.Series:
        """
        Collect the sorted unique values of columns, the shared body of every show_options().

        Args:
            selection (str | None): The column to show options for, or None for all columns.
            selection_values (list[str]): The columns that can be selected.
            invalid_selection_message (str): The error message for an invalid selection.
            filters (dict[str, Any]): Column name to a value or list of values.
            exclude_delisted (bool, optional): Whether to leave out delisted entries.
                Defaults to False.
            as_pandas (bool, optional): Whether to return numpy arrays instead of Polars
                Series. Defaults to True.

        Returns:
            dict | np.ndarray | pl.Series: The options of one column, or a dictionary with
                the options of every column.

        Raises:
            ValueError: If the selection is not one of the selection values.
        """
        if selection is not None and selection not in selection_values:
            raise ValueError(invalid_selection_message)
        lazy = self._filtered(filters, False, exclude_delisted)
        columns = selection_values if selection is None else [selection]
        frame = lazy.select(columns).collect()

        def options(column: str) -> np.ndarray | pl.Series:
            values = frame.get_column(column).drop_nulls().unique()
            if not as_pandas:
                return values.sort()
            # Sorted and deduplicated by pandas, exactly as the pandas implementation did.
            return (
                pd.Series(values.to_list(), dtype=string_dtype()).sort_values().unique()
            )

        if selection is None:
            return {column: options(column) for column in selection_values}
        return options(selection)

    def search(self, **kwargs: Any) -> pd.DataFrame | pl.DataFrame:
        """
        Search the database based on column names and queries, with optional case sensitivity.

        A query is a regular expression matched anywhere in the value; a list of queries
        keeps rows that contain any of them.

        Args:
            **kwargs: Column names and search queries.
                For example, symbol="TSLA" or sector="Technology".
            case_sensitive (bool, optional): Whether the search should be case-sensitive.
                Defaults to False.
            only_primary_listing (bool, optional): Whether to exclude secondary listings.
                Defaults to False.
            index (str, optional): Search within the DataFrame index. Defaults to None.
            exclude_delisted (bool, optional): Whether to exclude delisted entries (equities
                and ETFs). Defaults to True.
            as_pandas (bool, optional): Whether to return a pandas DataFrame (True) or a
                Polars DataFrame (False). Defaults to True.

        Returns:
            pd.DataFrame | pl.DataFrame: The rows matching every query.

        As an example:

        ```python
        import financedatabase as fd

        equities = fd.Equities()

        equities.search(
            summary="semiconductor", country="Netherlands", only_primary_listing=True
        )[["name", "currency", "industry", "exchange", "market_cap"]].head()
        ```

        Which returns:

        | symbol | name                             | currency | industry                                 | exchange | market_cap |
        |:-------|:---------------------------------|:---------|:-----------------------------------------|:---------|:-----------|
        | ASMIY  | ASM International N.V.           | USD      | Semiconductors & Semiconductor Equipment | PNK      | Large Cap  |
        | ASML   | ASML Holding N.V.                | USD      | Semiconductors & Semiconductor Equipment | NMS      | Mega Cap   |
        | ASMLF  | ASML Holding N.V.                | USD      | Semiconductors & Semiconductor Equipment | PNK      | Mega Cap   |
        | ASMXF  | ASM International N.V.           | USD      | Semiconductors & Semiconductor Equipment | PNK      | Large Cap  |
        | BESIY  | BE Semiconductor Industries N.V. | USD      | Semiconductors & Semiconductor Equipment | PNK      | Mid Cap    |
        """  # noqa: E501
        as_pandas = kwargs.pop("as_pandas", True) in [True, "True"]
        case_sensitive = kwargs.pop("case_sensitive", False) in [True, "True"]
        exclude_delisted = kwargs.pop("exclude_delisted", True) in [True, "True"]
        lazy = self._without_delisted(exclude_delisted)
        columns = [c for c in lazy.collect_schema().names() if c != ROW_POSITION]
        symbol = columns[0]

        for key, value in kwargs.items():
            if key == "only_primary_listing":
                if value is True:
                    lazy = lazy.filter(~pl.col(symbol).str.contains(".", literal=True))
            elif key == "index":
                if isinstance(value, list | pd.Index | pl.Series):
                    lazy = lazy.filter(pl.col(symbol).is_in(list(value)))
                else:
                    lazy = lazy.filter(_matches(pl.col(symbol), value, True))
            elif key not in columns[1:]:
                logger.warning("%s is not a valid column.", key)
            elif isinstance(value, list):
                if case_sensitive:
                    lazy = lazy.filter(pl.col(key).is_in(value))
                else:
                    lowered = pl.col(key).str.to_lowercase()
                    hits = [
                        lowered.str.contains(v.lower(), literal=True) for v in value
                    ]
                    lazy = lazy.filter(pl.any_horizontal(hits).fill_null(False))
            else:
                lazy = lazy.filter(_matches(pl.col(key), value, case_sensitive))

        return self._output(lazy.collect(), as_pandas)

    def show_options(self) -> pd.Index | dict | np.ndarray:
        """
        Get all available column options for the specific asset class.

        Subclasses override this method to return a richer payload (a dictionary keyed by
        column name, or the unique values of a single column).

        Returns:
            pd.Index | dict | np.ndarray: The column names of the asset class.
        """
        return self.data.columns


def _matches(column: pl.Expr, pattern: str, case_sensitive: bool) -> pl.Expr:
    """
    Match a regular expression with Python's semantics, as pandas' str.contains did.

    Polars' regex engine is used when it understands the pattern the same way; patterns it
    doesn't support (e.g. look-around or backreferences) fall back to Python's re module.

    Args:
        column (pl.Expr): The column to search.
        pattern (str): The regular expression.
        case_sensitive (bool): Whether the match is case-sensitive.

    Returns:
        pl.Expr: A boolean expression that is False for missing values.

    Raises:
        re.error: If the pattern is not a valid regular expression.
    """
    try:
        re.compile(pattern)
    except re.error as error:
        raise re.error(f"Invalid search pattern {pattern!r}: {error}") from error
    flagged = pattern if case_sensitive else f"(?i){pattern}"
    try:
        pl.select(pl.lit("").str.contains(flagged))
        return column.str.contains(flagged).fill_null(False)
    except pl.exceptions.ComputeError:
        compiled = re.compile(pattern, 0 if case_sensitive else re.IGNORECASE)
        return column.map_elements(
            lambda value: value is not None and bool(compiled.search(value)),
            return_dtype=pl.Boolean,
            skip_nulls=False,
        ).fill_null(False)


def show_options(
    selection: str | None = None,
    base_url: str = DATA_REPO,
    use_local_location: bool = False,
    as_pandas: bool = True,
) -> dict:
    """
    Get the available category options of an asset class without initializing it.

    Args:
        selection (str | None, optional): Asset class to get options for. Choose from:
            'equities', 'etfs', 'funds', 'indices', 'currencies', 'cryptos' or
            'moneymarkets'. Defaults to None.
        base_url (str, optional): Custom URL or file path location.
            Defaults to the GitHub repository.
        use_local_location (bool, optional): Whether to use the compressed files of a local
            copy of the repository. Defaults to False.
        as_pandas (bool, optional): Whether to return the values as numpy arrays (True) or
            as Polars Series (False). Defaults to True.

    Returns:
        dict: Category names mapped to their possible values.

    Raises:
        ValueError: If the selection is None or invalid, or the data can't be loaded.

    As an example:

    ```python
    import financedatabase as fd

    fd.show_options("equities")["sector"]
    ```

    Which returns:

    ```
    ['Communication Services', 'Consumer Discretionary', 'Consumer Staples', 'Energy',
     'Financials', 'Health Care', 'Industrials', 'Information Technology', 'Materials',
     'Real Estate', 'Utilities']
    ```
    """
    selection_values = [
        "equities",
        "etfs",
        "funds",
        "indices",
        "currencies",
        "cryptos",
        "moneymarkets",
    ]
    if selection is None:
        raise ValueError(
            "The 'selection' variable is not set. Please provide a valid selection.\n"
            f"The available options are: {', '.join(selection_values)}"
        )
    if selection not in selection_values:
        raise ValueError(
            f"The selection variable provided is not valid, "
            f"choose from {', '.join(selection_values)}"
        )

    the_path = str(COMPRESSION_PATH) + "/" if use_local_location else base_url
    the_path += f"/categories/{selection}_categories.gzip"

    try:
        if use_local_location:
            categories_df = pd.read_csv(
                the_path, compression="gzip", index_col=0, low_memory=False
            )
        else:
            response = requests.get(the_path, headers=HEADERS, timeout=60)
            response.raise_for_status()

            categories_df = pd.read_csv(
                BytesIO(response.content),
                compression="gzip",
                index_col=0,
                low_memory=False,
            )
    except requests.exceptions.RequestException as error:
        raise ValueError(
            f"Failed to load data from {the_path}: {str(error)}.\n{LOAD_ERROR_HINT}"
        ) from error

    categories = {
        index: categories_df.loc[index].dropna().to_numpy()
        for index in categories_df.index
    }
    if not as_pandas:
        return {
            index: pl.Series(index, [str(v) for v in values])
            for index, values in categories.items()
        }

    return categories
